/*
    CONSULTA DONDE SE PUEDEN VER LAS CATEGORIAS VISIBLES EN LA
    CONSOLA DEL USUARIO, LOS SERVICIOS A LOS QUE ESTAN ASOCIADOS
    Y EL CALENDARIO QUE TIENE ESE SERVICIO.
*/

SELECT
	A.NAME AS 'NOMBRE DEL SERVICIO',
	X.NAME AS 'NOMBRE DE SLA',
	Y.CALENDAR_NAME AS 'CALENDARIO',
	C.FL_STR_HIERARCHY AS 'JERARQUIA'
FROM
	ASDK_SLA AS X
INNER JOIN
	ASDK_SERVICE AS A
ON (X.SLA_ID = A.SLA_ID)
INNER JOIN
	ASDK_CALENDAR AS Y
ON (A.fl_int_calendar_id = Y.CALENDAR_ID) 
RIGHT JOIN
	ASDK_SERVICE_CATEGORY AS B
ON (A.FL_INT_SERVICE_ID = B.FL_INT_SERVICE_ID)
LEFT JOIN 
	ASDK_CATEGORY AS C
ON (B.CTG_INDEX = C.CTG_INDEX)
WHERE
	A.serv_status_id = 18 AND --SOLO SERVICIOS QUE ESTEN EN ESTADO ACTIVO
	C.fl_int_visibility = 1; --SOLO CATEGORIAS QUE ESTEN VISIBLES