SELECT 
	A.GRP_NAME AS 'NOMBRE DEL GRUPO',
	C.UNAME AS 'INTEGRANTE',
	CASE WHEN C.USER_ACTIVE = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS 'ESTADO DEL USUARIO'
FROM 
	GROUPHD AS A
INNER JOIN
	GROUP_USERS AS B
ON (A.GRP_ID = B.GRP_ID)
INNER JOIN
	USUARIOS AS C
ON (B.CODUSUARIO = C.CODUSUARIO);