SELECT
	A.serv_id_by_project AS 'ID',
	A.serv_subject AS 'ASUNTO',
	C.TASKNAME AS 'NOMBRE DE LA TAREA',
	C.DESCRIPTION AS 'DESCRIPCIÓN DE LA TAREA',
	D.stat_name AS 'ESTADO',
	E.UNAME AS 'USUARIO A CARGO',
	F.GRP_NAME AS 'GRUPO',
	C.DATEINI AS 'FECHA INICIAL',
	C.DATEEND AS 'FECHA FINAL'
FROM
	ASDK_SERVICE_CALL AS A
INNER JOIN
	ASDK_SERVICECALL_TASK AS B
ON (A.serv_id = B.serv_id)
INNER JOIN
	ASDK_TASK AS C
ON (C.ID_TASK = B.task_id)
INNER JOIN 
	AFW_STATUS AS D 
ON (C.TASK_STATUS = D.stat_id)
INNER JOIN
	USUARIOS AS E
ON (C.RESPONSABLEID = E.CODUSUARIO)
INNER JOIN 
	GROUPHD AS F
ON (F.GRP_ID = C.GRP_ID);