/*
OBTIENE LAS TRANSFERENCIAS DE GRUPOS QUE SE HAYAN EJECUTADO
SOBRE UN INCIDENTE O REQUERIMIENTO

CREA UNA TABLA TEMPORAL DONDE ALMACENA EL ID GLOBAL DEL CASO Y EL ID POR PROYECTO
QUE SE USARA PARA UNIRLA A LA TABLA DE ENRUTAMIENTO HISTORICO
*/

BEGIN

    CREATE TABLE #ALL_CASES(
        id_global integer not null,
        id_project integer not null
    ) --CREACION DE TABLA TEMPORAL PARA LOS COD DE INCIDENTES Y REQUERIMIENTOS
    
    INSERT #ALL_CASES
    SELECT inci_id AS 'id_global', inci_id_by_project AS 'id_project' FROM ASDK_INCIDENT
    UNION
    SELECT serv_id AS 'id_global', serv_id_by_project AS 'id_project' FROM ASDK_SERVICE_CALL

END

SELECT
    CASE
        WHEN Y.achi_row_type = 4 THEN 'REQUERIMIENTO'
        ELSE 'INCIDENTE'
    END AS 'TIPO DE CASO',
    ALL_CASES.id_project AS 'NUMERO CASO',
	G1.GRP_NAME AS 'GRUPO ANTERIOR',
	G2.GRP_NAME AS 'GRUPO NUEVO',
	U1.UNAME AS 'ESPECIALISTA ANTERIOR',
	U2.UNAME AS 'ESPECIALISTA NUEVO',
	Y.achi_created AS 'FECHA'
FROM
	GROUPHD AS G1 --GRUPO ANTIGUO
INNER JOIN
	ASDK_ROUTER_HIST AS X
ON(X.rohi_old_group = G1.GRP_ID)
INNER JOIN
	GROUPHD AS G2 --GRUPO NUEVO
ON(X.rohi_new_group = G2.GRP_ID)
INNER JOIN
	USUARIOS AS U1 --ESPECIALISTA ANTIGUO
ON(X.rohi_old_user = U1.CODUSUARIO)
INNER JOIN
	USUARIOS AS U2 --ESPECIALISTA NUEVO
ON(X.rohi_new_user = U2.CODUSUARIO)
INNER JOIN
	ASDK_ACTION_HIST AS Y --PARA OBTENER LA FECHA DE REGISTO DE ACCIÓN
ON(X.rohi_action_hist_id = Y.achi_id)
INNER JOIN
    #ALL_CASES AS ALL_CASES
ON (ALL_CASES.id_global = Y.achi_item_id)
WHERE
    Y.achi_row_type IN (1,4) --SOLO REQUERIMIENTOS E INCIDENTES
