--VISTA QUE SE ENLAZA CON LA HOJA "Tickets del día" DEL LIBRO "REPORTES DIARIOS FONAFE" DONDE SE OBTIENE LOS TICKETS DEL DIA.

--ESTE SE CONSIDERA UN REPORTE DIARIO.

--LA PRIMERA PARTE DE LA CONSULTA RETORNA LOS INCIDENTES Y LA SEGUNDA LOS REQ. DE SERVICIO.

CREATE VIEW VISTA_INC_REQ_DIAR AS
(
	--CONSULTA DE INCIDENTES
	SELECT
		'INC' AS 'TIPO DE CASO',
		T2.inci_id_by_project AS 'NRO DE CASO',
		T2.inci_subject AS 'ASUNTO',
		FORMAT(T2.inci_opened_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA DE REGISTRO',
		T1.stat_name AS 'ESTADO',
		T3.UNAME AS 'CLIENTE',
		T4.GRP_NAME AS 'GRUPO',
		FORMAT(T2.inci_expired_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA ESTIMADA DE SOLUCIÓN'
	FROM
		(SELECT AFW_STATUS.stat_id, AFW_STATUS.stat_name FROM AFW_STATUS WHERE AFW_STATUS.stat_app_category = 1) AS T1
	INNER JOIN ASDK_INCIDENT AS T2 ON
		(T2.inci_status_id = T1.stat_id)
	INNER JOIN USUARIOS AS T3 ON
		(T2.inci_customer_id = T3.CODUSUARIO)
	INNER JOIN GROUPHD AS T4 ON
		(T2.inci_responsible_group_id = T4.GRP_ID)
	WHERE
		CONVERT(VARCHAR, T2.inci_opened_date, 3) = CONVERT(VARCHAR, GETDATE(), 3)
		-- NO SE TOMAN EN CUENTA LOS TICKETS QUE SE HAYAN ANULADO
		AND T1.stat_name NOT IN ('Anulado')
		
	UNION ALL
	
	--REQUERIMIENTOS DE SERVICIO
	SELECT
		'REQ' AS 'TIPO DE CASO',
		T2.serv_id_by_project AS 'NRO DE CASO',
		T2.serv_subject AS 'ASUNTO',
		FORMAT(T2.serv_opened_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA DE REGISTRO',
		T1.stat_name AS 'ESTADO',
		T3.UNAME AS 'CLIENTE',
		T4.GRP_NAME AS 'GRUPO',
		FORMAT(T2.serv_expired_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA ESTIMADA DE SOLUCIÓN'
	FROM
		(SELECT AFW_STATUS.stat_id, AFW_STATUS.stat_name FROM AFW_STATUS WHERE AFW_STATUS.stat_app_category = 4) AS T1
	INNER JOIN ASDK_SERVICE_CALL AS T2 ON
		(T2.serv_status_id = T1.stat_id)
	INNER JOIN USUARIOS AS T3 ON
		(T2.serv_customer_id = T3.CODUSUARIO)
	INNER JOIN GROUPHD AS T4 ON
		(T2.serv_responsible_group_id = T4.GRP_ID)
	WHERE
		CONVERT(VARCHAR, T2.serv_opened_date, 3) = CONVERT(VARCHAR, GETDATE(), 3)
		--NO SE TOMAN EN CUENTA LOS TICKETS QUE SE HAYAN ANULADO
		AND T1.stat_name NOT IN ('Anulado')
)