CREATE VIEW ALL_CATEGORY 
AS
    (
    SELECT
        A.CTG_INDEX AS 'ID',
        CONCAT(C.CTG_CAPTION, '/', B.CTG_CAPTION, '/', A.CTG_CAPTION) AS 'CONCAT_CAT'
    FROM 
        ASDK_CATEGORY AS A
    INNER JOIN 
        ASDK_CATEGORY AS B
    ON 
        A.CTG_PARENT = B.CTG_INDEX
    INNER JOIN 
        ASDK_CATEGORY AS C
    ON 
        B.CTG_PARENT = C.CTG_INDEX
    WHERE
        C.CTG_PARENT IS NULL

    UNION
        
    SELECT
        A.CTG_INDEX AS 'ID',
        CONCAT(D.CTG_CAPTION, '/', C.CTG_CAPTION, '/', B.CTG_CAPTION, '/', A.CTG_CAPTION) AS 'CONCAT_CAT'
    FROM 
        ASDK_CATEGORY AS A
    INNER JOIN 
        ASDK_CATEGORY AS B
    ON 
        A.CTG_PARENT = B.CTG_INDEX
    INNER JOIN 
        ASDK_CATEGORY AS C
    ON 
        B.CTG_PARENT = C.CTG_INDEX
    INNER JOIN
        ASDK_CATEGORY AS D
    ON
        C.CTG_PARENT = D.CTG_INDEX
    )