SELECT
    A.GRP_ID AS 'ID DEL GRUPO',
    A.GRP_NAME AS 'NOMBRE DE GRUPO',
    B.UNAME AS 'RESPONSABLE',
    CASE WHEN A.Active = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS 'ESTADO DEL GRUPO',
    CASE WHEN B.USER_ACTIVE = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS 'ESTADO DEL RESPONSABLE'
FROM
    GROUPHD AS A
INNER JOIN  
    USUARIOS AS B 
ON (A.GRP_USER = B.CODUSUARIO);