--VISTA QUE SE ENLAZA CON LA HOJA "ACTIVIDAD Y PROYECTOS" DEL LIBRO "REPORTES DIARIOS FONAFE" DONDE SE OBTIENE LAS ACTIVIDADDES TIPO INCIDENTES Y REQUERIMIENTOS DE SERVICIO. 

--ESTE SE CONSIDERA UN REPORTE HISTORICO

--LA PRIMERA PARTE DE LA CONSULTA RETORNA LOS INCIDENTES Y LA SEGUNDA LOS REQ. DE SERVICIO.

CREATE VIEW VISTA_ACT_PRO_HIST AS
(
--CONSULTA DE ACTIVIDADES TIPO INCIDENTE
SELECT
	'INC' AS 'TIPO DE CASO',
	T2.inci_id_by_project AS 'NRO DE CASO',
	T2.inci_subject AS 'ASUNTO',
	FORMAT(T2.inci_opened_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA DE REGISTRO',
	T1.stat_name AS 'ESTADO',
	T3.UNAME AS 'CLIENTE',
	T4.GRP_NAME AS 'GRUPO',
	FORMAT(T2.inci_expired_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA ESTIMADA DE SOLUCIÓN'
FROM
	--CONSULTA A LA TABLA DE ESTADOS PARA PODER HACER FILTROS. SOLO SE TOMA LOS ESTADOS QUE PUEDE TENER UN CASO (REGISTRADO, ASIGNADO, EN PROCESO, ETC)
	(SELECT AFW_STATUS.stat_id, AFW_STATUS.stat_name FROM AFW_STATUS WHERE AFW_STATUS.stat_app_category = 1) AS T1
INNER JOIN ASDK_INCIDENT AS T2 ON
	(T2.inci_status_id = T1.stat_id)
INNER JOIN USUARIOS AS T3 ON
	(T2.inci_customer_id = T3.CODUSUARIO)
INNER JOIN GROUPHD AS T4 ON
	(T2.inci_responsible_group_id = T4.GRP_ID)
INNER JOIN ASDK_SERVICE AS T5 ON
	(T5.FL_INT_SERVICE_ID = T2.inci_service_id)
WHERE
	T5.NAME = 'Desarrollo de aplicaciones internas y corporativo' AND
	--SOLO SE INCLUIRAN LOS CASOS QUE NO TENGAN LOS SIGUIENTES ESTADOS
	T1.stat_name NOT IN ('Solucionado', 'Cerrado', 'Anulado')

UNION
--REQUERIMIENTOS DE SERVICIO
SELECT
	'REQ' AS 'TIPO DE CASO',
	T2.serv_id_by_project AS 'NRO DE CASO',
	T2.serv_subject AS 'ASUNTO',
	FORMAT(T2.serv_opened_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA DE REGISTRO',
	T1.stat_name AS 'ESTADO',
	T3.UNAME AS 'CLIENTE',
	T4.GRP_NAME AS 'GRUPO',
	FORMAT(T2.serv_expired_date, 'dd/MM/yyyy HH:mm:ss') AS 'FECHA ESTIMADA DE SOLUCIÓN'
FROM
	--CONSULTA A LA TABLA DE ESTADOS PARA PODER HACER FILTROS. SOLO SE TOMA LOS ESTADOS QUE PUEDE TENER UN CASO (REGISTRADO, ASIGNADO, EN PROCESO, ETC)
	(SELECT AFW_STATUS.stat_id, AFW_STATUS.stat_name FROM AFW_STATUS WHERE AFW_STATUS.stat_app_category = 4) AS T1
INNER JOIN ASDK_SERVICE_CALL AS T2 ON
	(T2.serv_status_id = T1.stat_id)
INNER JOIN USUARIOS AS T3 ON
	(T2.serv_customer_id = T3.CODUSUARIO)
INNER JOIN GROUPHD AS T4 ON
	(T2.serv_responsible_group_id = T4.GRP_ID)
INNER JOIN ASDK_SERVICE AS T5 ON
	(T5.FL_INT_SERVICE_ID = T2.serv_service_id)
WHERE
	T5.NAME = 'Desarrollo de aplicaciones internas y corporativo' AND
	--SOLO SE INCLUIRAN LOS CASOS QUE NO TENGAN LOS SIGUIENTES ESTADOS
	T1.stat_name NOT IN ('Solucionado', 'Cerrado', 'Anulado')
)