CREATE VIEW ALL_CATEGORY 
AS
    (
    SELECT
		C.CTG_CAPTION AS 'CATEGORIA 1',
		B.CTG_CAPTION AS 'CATEGORIA 2',
		A.CTG_CAPTION AS 'CATEGORIA 3',
		NULL AS 'CATEGORIA 4'
	FROM
		ASDK_CATEGORY AS A
	INNER JOIN 
        ASDK_CATEGORY AS B
	ON 
        A.CTG_PARENT = B.CTG_INDEX
	INNER JOIN 
        ASDK_CATEGORY AS C
	ON 
        B.CTG_PARENT = C.CTG_INDEX
	WHERE
		C.CTG_PARENT IS NULL
	
	UNION
	        
	SELECT
		D.CTG_CAPTION AS 'CATEGORIA 1',
		C.CTG_CAPTION AS 'CATEGORIA 2',
		B.CTG_CAPTION AS 'CATEGORIA 3',
		A.CTG_CAPTION AS 'CATEGORIA 4'
	FROM
		ASDK_CATEGORY AS A
	INNER JOIN 
	    ASDK_CATEGORY AS B
	ON
		A.CTG_PARENT = B.CTG_INDEX
	INNER JOIN 
	    ASDK_CATEGORY AS C
	ON
		B.CTG_PARENT = C.CTG_INDEX
	INNER JOIN
	    ASDK_CATEGORY AS D
	ON
		C.CTG_PARENT = D.CTG_INDEX
    )