SELECT
    TIPO_CASO,
    NUMERO_CASO,
    ID_INTERNO_DEL_CASO,
    CATEGORIA,
    SERVICIO,
    JERARQUIA,
    CP_APLICA_A,
    CP_SEDE_AFECTADA,
    CA_CONTROL_REMOTO,
    CA_TICKET_EXTERNO,
    CA_SOLICITANTE,
    CA_INCIDENTE_MAYOR,
    CP_FECHA_CORREO,
    CP_NRO_ATENCIONES,
    MOTIVOPROGRAMADO,
    FECHAPROGRAMADO,
    NOMBREPROVEEDOR,
    TICKETPROVEEDOR,
    NEWAPLICA,
    DESCRIPCION,
    AUTOR,
    ESPECIALISTA,
    GRUPO,
    ESTADO,
    RAZON,
    TICKET_EXONERADO,
    USUARIO,
    USUARIO_ALIAS,
    USUARIO_PHONE1,
    TIPO_DE_USUARIO,
    DEPARTAMENTO_USUARIO,
    CARGO,
    SUCURSAL_USUARIO,
    SEDE_USUARIO,
    EDIFICIO_USUARIO,
    FECHA_REGISTRO FECHA_DE_APERTURA,
    TIPO_REGISTRO METODO_DE_REPORTE,
    FECHA_MAX_ATENCION,
    FECHA_MAX_SOLUCION,
    FECHA_SOLUCION,
    FECHA_CIERRE,
    IMPACTO,
    URGENCIA,
    PRIORIDAD,
    SLA_NOMBRE,
    TIEMPO_ATENCION_REAL,
    TIEMPO_CASO,
    TIEMPO_ATENCION_ESTIMADO,
    TIEMPO_SOLUCION_ESTIMADO,
    (TIEMPO_ATENCION_ESTIMADO + TIEMPO_SOLUCION_ESTIMADO) TR_OBJETIVO_MINS,
    TIEMPO_SOLUCION_REAL,
    ULTIMO_INCIDENTE_ASOCIADO,
    ULTIMO_PROBLEMA_ASOCIADO,
    ULTIMO_REQUERIMIENTO_ASOCIADO,
    COMENTARIO_SOLUCION,
    CI_ASOCIADO,
    CP_TIPO_PROBLEMA,
    CP_CODIGO_CORRECTIVO,
    CP_WORKAROUND,
    CP_CAUSA_RAIZ,
    CAUSA CAUSA_DEL_PROBLEMA,
    CASE
        WHEN LOWER(ESTADO) NOT IN ('CANCELADO', 'CERRADO', 'ANULADO') 
        THEN (DBO.FUN_ASDK_TOTAL_TIME(7,FECHA_REGISTRO,GETDATE()) / 86400)
    ELSE NULL
    END CANTIDAD_DE_DIAS_ABIERTO,
    CATEGORIA_ESPECIALISTA,
    DETALLEPENDIENTE
FROM
    (
        SELECT
            ASVC.SERV_ID_BY_PROJECT NUMERO_CASO,
            ASVC.SERV_ID ID_INTERNO_DEL_CASO,
            'REQUERIMIENTO' TIPO_CASO,
            CATEGORY_DESC CATEGORIA,
            CATEGORY_HIERARCHY JERARQUIA,
            ASVC.ADD_STR_1 CP_APLICA_A,
            ASVC.ADD_STR_2 CP_SEDE_AFECTADA,
            ASVC.ADD_STR_4 CA_CONTROL_REMOTO,
            ASVC.ADD_STR_5 CA_TICKET_EXTERNO,
            ASVC.ADD_STR_6 CA_SOLICITANTE,
            NULL CA_INCIDENTE_MAYOR,
            ASVC.ADD_STR_7 CP_FECHA_CORREO,
            ASVC.ADD_STR_8 CP_NRO_ATENCIONES,
            NULL CP_WORKAROUND,
            NULL CP_CODIGO_CORRECTIVO,
            NULL CP_TIPO_PROBLEMA,
            NULL CP_CAUSA_RAIZ,
            (
                SELECT
                    FL_STR_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_SERVICE_CALL.SERV_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 233
            ) MOTIVOPROGRAMADO,
            (
                SELECT
                    FL_DATE_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_SERVICE_CALL.SERV_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 231
            ) FECHAPROGRAMADO,
            NULL NOMBREPROVEEDOR,
            NULL TICKETPROVEEDOR,
            (
                SELECT
                    FL_STR_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_SERVICE_CALL.SERV_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 28
            ) NEWAPLICA,
            --, REPLACE(REPLACE(DBO.DESC_BLANK_QM(DBO.DESC_CASOS(ASVC.SERV_DESCRIPTION)), '<', ''), '>', '') DESCRIPCION
            --,ASVC.SERV_DESCRIPTION DESCRIPCION
            --, DBO.REMOVE_HTML(ASVC.SERV_DESCRIPTION) DESCRIPCION
            DBO.REMOVE_HTML(REPLACE(REPLACE(DBO.DESC_BLANK_QM(DBO.DESC_CASOS(ASVC.SERV_DESCRIPTION)), '<', ''), '>', '')) DESCRIPCION,
            USUAUTOR.UNAME AUTOR,
            USURECEPTOR.UNAME RECEPTOR,
            USUESPECIALISTA.UNAME ESPECIALISTA,
            RESPONSIBLE_GROUP_DESC GRUPO,
            STATUS_DESC ESTADO,
            REASON_DESC RAZON,
            (
                SELECT
                    TOP 1 FL_INT_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                INNER JOIN AFW_ADD_FIELDS_CONFIG ON
                    AFW_ADD_FIELDS_DATA.FL_INT_ID_FIELD = AFW_ADD_FIELDS_CONFIG.FL_INT_ID_FIELD
                WHERE
                    FL_INT_ID_CASO = ASVC.SERV_ID
                    AND AFW_ADD_FIELDS_CONFIG.FL_STR_NAME = 'EXONERADO'
                ORDER BY
                    FL_INT_ID_DATA DESC
            ) TICKET_EXONERADO,
            VENDOR.COMPANY COMPANIA,
            COUNTRYVENDOR.DESCRIPTION PAIS_COMPANIA,
            CLIENTE.UNAME USUARIO,
            CLIENTE.USERNAME USUARIO_ALIAS,
            CLIENTE.PHONE1 USUARIO_PHONE1,
            CLIENTE.DES_USER_STATUS TIPO_DE_USUARIO,
            CLIENTE.DES_COUNTRY PAIS_USUARIO,
            CLIENTE.DES_DEPARTAMENTO DEPARTAMENTO_USUARIO,
            CLIENTE.DES_CARGO CARGO,
            CLIENTE.DES_COMPANY SUCURSAL_USUARIO,
            CLIENTE.DES_SITE SEDE_USUARIO,
            CLIENTE.DES_BUILDING EDIFICIO_USUARIO,
            ASVC.SERV_OPENED_DATE FECHA_REGISTRO,
            REGISTRY_TYPE_DESC TIPO_REGISTRO,
            ASVC.SERV_COLSED_DATE FECHA_CIERRE,
            ASVC.SERV_ATTENTION_REAL_DATE FECHA_ATENCION,
            ASVC.SERV_SOLUTION_REAL_DATE FECHA_SOLUCION,
            IMPACT_DESC IMPACTO,
            URGENCY_DESC URGENCIA,
            PRIORITY_DESC PRIORIDAD,
            ASDK_SERVICE.NAME SERVICIO,
            ASDK_SERVICE.FL_INT_CALENDAR_ID IDCALENDARIO,
            ASDK_SLA.NAME SLA_NOMBRE,
            ASVC.SERV_EXPIRED_DATE FECHA_MAX_SOLUCION,
            ASVC.SERV_ATTENTION_ESTI_DATE FECHA_MAX_ATENCION,
            ISNULL(ASVC.SERV_CURRENT_TIME, 0) TIEMPO_CASO,
            ISNULL(ASVC.SERV_CURRENT_PROGRESS, 0) PROGRESO_CASO,
            ISNULL(ASVC.SERV_ATTENTION_TIME, 0) TIEMPO_ATENCION_ESTIMADO,
            ISNULL(ASVC.SERV_ATTENTION_REAL_TIME, 0) TIEMPO_ATENCION_REAL,
            ISNULL(ASVC.SERV_SOLUTION_TIME, 0) TIEMPO_SOLUCION_ESTIMADO,
            ISNULL(ASVC.SERV_SOLUTION_REAL_TIME, 0) TIEMPO_SOLUCION_REAL,
            (
                SELECT
                    TOP 1 INCI.INCI_ID_BY_PROJECT ULTIMOINCIASOCIADO
                FROM
                    ASDK_INCIDENT_SERVICE_CALL
                LEFT OUTER JOIN ASDK_INCIDENT INCI ON
                    ASDK_INCIDENT_SERVICE_CALL.INCH_INCI_ID = INCI.INCI_ID
                WHERE
                    ASDK_INCIDENT_SERVICE_CALL.INCH_SERV_ID = ASVC.SERV_ID
                ORDER BY
                    ASDK_INCIDENT_SERVICE_CALL.INCH_CREATED DESC
            ) ULTIMO_INCIDENTE_ASOCIADO,
            (
                SELECT
                    TOP 1 PROB.PROB_ID_BY_PROJECT ULTIMOPROBASOCIADO
                FROM
                    ASDK_SERVICE_CALL_PROBLEM
                LEFT OUTER JOIN ASDK_PROBLEM PROB ON
                    ASDK_SERVICE_CALL_PROBLEM.INPR_PROB_ID = PROB.PROB_ID
                WHERE
                    ASDK_SERVICE_CALL_PROBLEM.INPR_SERV_ID = ASVC.SERV_ID
                ORDER BY
                    ASDK_SERVICE_CALL_PROBLEM.INPR_CREATED DESC
            ) ULTIMO_PROBLEMA_ASOCIADO,
            (
                SELECT
                    TOP 1 SERV.SERV_ID_BY_PROJECT ULTIMOCAMBIOASOCIADO
                FROM
                    ASDK_SERVICE_CALL_SELF
                LEFT OUTER JOIN ASDK_SERVICE_CALL SERV ON
                    ASDK_SERVICE_CALL_SELF.INSE_SERV_CHILD_ID = SERV.SERV_ID
                WHERE
                    ASDK_SERVICE_CALL_SELF.INSE_SERV_PARENT_ID = ASVC.SERV_ID
                ORDER BY
                    ASDK_SERVICE_CALL_SELF.INSE_CREATED DESC
            ) ULTIMO_REQUERIMIENTO_ASOCIADO,
            REPLACE(REPLACE(DBO.DESC_BLANK_QM(DBO.DESC_CASOS(ASVC.SERV_COMMENTARY)), '<', ''), '>', '') COMENTARIO_SOLUCION,
            (
                SELECT
                    CI_CONFIGURATION_ITEM.FL_STR_CI_NAME
                FROM
                    CI_CONFIGURATION_ITEM
                WHERE
                    CI_CONFIGURATION_ITEM.FL_INT_CI_ID = ASVC.SERV_ASSOCIATED_CI
            ) CI_ASOCIADO,
            NULL CAUSA,
            (
                SELECT
                    UNAME
                FROM
                    ASDK_CATEGORY
                LEFT OUTER JOIN USUARIOS ON
                    FL_INT_COD_ESPECIALISTA = CODUSUARIO
                WHERE
                    CTG_INDEX = SERV_CATEGORY_ID
            ) CATEGORIA_ESPECIALISTA,
            ASVC.ADD_STR_3 DETALLEPENDIENTE
        FROM
            ASDK_SERVICE_CALL ASVC
            LEFT OUTER JOIN V_ASDK_SERVICE_CALL ON
                V_ASDK_SERVICE_CALL.SERV_ID = ASVC.SERV_ID
            LEFT OUTER JOIN USUARIOS USUAUTOR ON
                USUAUTOR.CODUSUARIO = ASVC.SERV_AUTHOR
            LEFT OUTER JOIN USUARIOS USURECEPTOR ON
                USURECEPTOR.CODUSUARIO = ASVC.SERV_CODRECEPTOR
            LEFT OUTER JOIN USUARIOS USUESPECIALISTA ON
                USUESPECIALISTA.CODUSUARIO = ASVC.SERV_RESPONSIBLE_ID
            LEFT OUTER JOIN VIEW_USERS CLIENTE ON
                CLIENTE.CODUSUARIO = ASVC.SERV_CUSTOMER_ID
            LEFT OUTER JOIN VENDOR ON
                VENDOR.VENDORID = ASVC.SERV_VENDOR_ID
            LEFT OUTER JOIN COUNTRY COUNTRYVENDOR ON
                COUNTRYVENDOR.COUNTRYID = VENDOR.COUNTRYID
            LEFT OUTER JOIN ASDK_SERVICE ON
                ASDK_SERVICE.FL_INT_SERVICE_ID = ASVC.SERV_SERVICE_ID
            LEFT OUTER JOIN ASDK_SLA ON
                ASDK_SLA.SLA_ID = ASVC.SERV_SERVICE_SLA_ID

        UNION ALL

        SELECT
            AIC.INCI_ID_BY_PROJECT NUMERO_CASO,
            AIC.INCI_ID ID_INTERNO_DEL_CASO,
            'INCIDENTE' TIPO_CASO,
            CATEGORY_DESC CATEGORIA,
            CATEGORY_HIERARCHY JERARQUIA,
            AIC.ADD_STR_1 CP_APLICA_A,
            AIC.ADD_STR_2 CP_SEDE_AFECTADA,
            AIC.ADD_STR_4 CA_CONTROL_REMOTO,
            NULL CA_TICKET_EXTERNO,
            AIC.ADD_STR_6 CA_SOLICITANTE,
            AIC.ADD_STR_5 CA_INCIDENTE_MAYOR,
            AIC.ADD_STR_7 CP_FECHA_CORREO,
            NULL CP_NRO_ATENCIONES,
            NULL CP_WORKAROUND,
            NULL CP_CODIGO_CORRECTIVO,
            NULL CP_TIPO_PROBLEMA,
            NULL CP_CAUSA_RAIZ,
            (
                SELECT
                    FL_STR_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_INCIDENTS.INCI_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 3
            ) MOTIVOPROGRAMADO,
            (
                SELECT
                    FL_DATE_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_INCIDENTS.INCI_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 229
            ) FECHAPROGRAMADO,
            (
                SELECT
                    FL_STR_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_INCIDENTS.INCI_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 1
            ) NOMBREPROVEEDOR,
            (
                SELECT
                    FL_STR_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_INCIDENTS.INCI_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 2
            ) TICKETPROVEEDOR,
            (
                SELECT
                    FL_STR_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                WHERE
                    V_ASDK_INCIDENTS.INCI_ID = AFW_ADD_FIELDS_DATA.FL_INT_ID_CASO
                    AND FL_INT_ID_FIELD = 27
            ) NEWAPLICA,
            --, REPLACE(REPLACE(DBO.DESC_BLANK_QM(DBO.DESC_CASOS(AIC.INCI_DESCRIPTION)), '<', ''), '>', '') DESCRIPCION
            --,AIC.INCI_DESCRIPTION DESCRIPCION
            --,DBO.REMOVE_HTML( AIC.INCI_DESCRIPTION) DESCRIPCION
            DBO.REMOVE_HTML(REPLACE(REPLACE(DBO.DESC_BLANK_QM(DBO.DESC_CASOS(AIC.INCI_DESCRIPTION)), '<', ''), '>', '')) DESCRIPCION,
            USUAUTOR.UNAME AUTOR,
            USURECEPTOR.UNAME RECEPTOR,
            USUESPECIALISTA.UNAME ESPECIALISTA,
            RESPONSIBLE_GROUP_DESC GRUPO,
            STATUS_DESC ESTADO,
            REASON_ID RAZON,
            (
                SELECT
                    TOP 1 FL_INT_FIELD_VALUE
                FROM
                    AFW_ADD_FIELDS_DATA
                INNER JOIN AFW_ADD_FIELDS_CONFIG ON
                    AFW_ADD_FIELDS_DATA.FL_INT_ID_FIELD = AFW_ADD_FIELDS_CONFIG.FL_INT_ID_FIELD
                WHERE
                    FL_INT_ID_CASO = AIC.INCI_ID
                    AND AFW_ADD_FIELDS_CONFIG.FL_STR_NAME = 'EXONERADO'
                ORDER BY
                    FL_INT_ID_DATA DESC
            ) TICKET_EXONERADO,
            VENDOR.COMPANY COMPANIA,
            COUNTRYVENDOR.DESCRIPTION PAIS_COMPANIA,
            CLIENTE.UNAME USUARIO,
            CLIENTE.USERNAME USUARIO_ALIAS,
            CLIENTE.PHONE1 USUARIO_PHONE1,
            CLIENTE.DES_USER_STATUS TIPO_DE_USUARIO,
            CLIENTE.DES_COUNTRY PAIS_USUARIO,
            CLIENTE.DES_DEPARTAMENTO DEPARTAMENTO_USUARIO,
            CLIENTE.DES_CARGO CARGO,
            CLIENTE.DES_COMPANY SUCURSAL_USUARIO,
            CLIENTE.DES_SITE SEDE_USUARIO,
            CLIENTE.DES_BUILDING EDIFICIO_USUARIO,
            AIC.INCI_OPENED_DATE FECHA_REGISTRO,
            REGISTRY_TYPE_DESC TIPO_REGISTRO,
            AIC.INCI_COLSED_DATE FECHA_CIERRE,
            AIC.INCI_ATTENTION_REAL_DATE FECHA_ATENCION,
            AIC.INCI_SOLUTION_REAL_DATE FECHA_SOLUCION,
            IMPACT_DESC IMPACTO,
            URGENCY_DESC URGENCIA,
            PRIORITY_DESC PRIORIDAD,
            ASDK_SERVICE.NAME SERVICIO,
            ASDK_SERVICE.FL_INT_CALENDAR_ID IDCALENDARIO,
            ASDK_SLA.NAME SLA_NOMBRE,
            AIC.INCI_EXPIRED_DATE FECHA_MAX_SOLUCION,
            AIC.INCI_ATTENTION_ESTI_DATE FECHA_MAX_ATENCION,
            ISNULL(AIC.INCI_CURRENT_TIME, 0) TIEMPO_CASO,
            ISNULL(AIC.INCI_CURRENT_PROGRESS, 0) PROGRESO_CASO,
            ISNULL(AIC.INCI_ATTENTION_TIME, 0) TIEMPO_ATENCION_ESTIMADO,
            ISNULL(AIC.INCI_ATTENTION_REAL_TIME, 0) TIEMPO_ATENCION_REAL,
            ISNULL(AIC.INCI_SOLUTION_TIME, 0) TIEMPO_SOLUCION_ESTIMADO,
            ISNULL(AIC.INCI_SOLUTION_REAL_TIME, 0) TIEMPO_SOLUCION_REAL,
            (
                SELECT
                    TOP 1 INCI.INCI_ID_BY_PROJECT ULTIMOINCIASOCIADO
                FROM
                    ASDK_INCIDENT_SELF
                LEFT OUTER JOIN ASDK_INCIDENT INCI ON
                    ASDK_INCIDENT_SELF.INSE_INCI_CHILD_ID = INCI.INCI_ID
                WHERE
                    ASDK_INCIDENT_SELF.INSE_INCI_PARENT_ID = AIC.INCI_ID
                ORDER BY
                    INSE_CREATED DESC
            ) ULTIMO_INCIDENTE_ASOCIADO,
            (
                SELECT
                    TOP 1 PROB.PROB_ID_BY_PROJECT ULTIMOPROBASOCIADO
                FROM
                    ASDK_INCIDENT_PROBLEM
                LEFT OUTER JOIN ASDK_PROBLEM PROB ON
                    ASDK_INCIDENT_PROBLEM.INPR_PROB_ID = PROB.PROB_ID
                WHERE
                    ASDK_INCIDENT_PROBLEM.INPR_INCI_ID = AIC.INCI_ID
                ORDER BY
                    ASDK_INCIDENT_PROBLEM.INPR_CREATED DESC
            ) ULTIMO_PROBLEMA_ASOCIADO,
            (
                SELECT
                    TOP 1 SERV.SERV_ID_BY_PROJECT ULTIMOPROBASOCIADO
                FROM
                    ASDK_INCIDENT_SERVICE_CALL
                LEFT OUTER JOIN ASDK_SERVICE_CALL SERV ON
                    ASDK_INCIDENT_SERVICE_CALL.INCH_SERV_ID = SERV.SERV_ID
                WHERE
                    ASDK_INCIDENT_SERVICE_CALL.INCH_INCI_ID = AIC.INCI_ID
                ORDER BY
                    ASDK_INCIDENT_SERVICE_CALL.INCH_CREATED DESC
            ) ULTIMO_REQUERIMIENTO_ASOCIADO,
            REPLACE(REPLACE(DBO.DESC_BLANK_QM(DBO.DESC_CASOS(AIC.INCI_COMMENTARY)), '<', ''), '>', '') COMENTARIO_SOLUCION,
            (
                SELECT
                    CI_CONFIGURATION_ITEM.FL_STR_CI_NAME
                FROM
                    CI_CONFIGURATION_ITEM
                WHERE
                    CI_CONFIGURATION_ITEM.FL_INT_CI_ID = AIC.INCI_ASSOCIATED_CI
            ) CI_ASOCIADO,
            '' CAUSA,
            (
                SELECT
                    UNAME
                FROM
                    ASDK_CATEGORY
                LEFT OUTER JOIN USUARIOS ON
                    FL_INT_COD_ESPECIALISTA = CODUSUARIO
                WHERE
                    CTG_INDEX = INCI_CATEGORY_ID
            ) CATEGORIA_ESPECIALISTA,
            AIC.ADD_STR_9 DETALLEPENDIENTE
        FROM
            ASDK_INCIDENT AIC
            LEFT OUTER JOIN V_ASDK_INCIDENTS ON
                AIC.INCI_ID = V_ASDK_INCIDENTS.INCI_ID
            LEFT OUTER JOIN USUARIOS USUAUTOR ON
                USUAUTOR.CODUSUARIO = AIC.INCI_AUTHOR
            LEFT OUTER JOIN USUARIOS USURECEPTOR ON
                USURECEPTOR.CODUSUARIO = AIC.INCI_CODRECEPTOR
            LEFT OUTER JOIN USUARIOS USUESPECIALISTA ON
                USUESPECIALISTA.CODUSUARIO = AIC.INCI_RESPONSIBLE_ID
            LEFT OUTER JOIN VIEW_USERS CLIENTE ON
                CLIENTE.CODUSUARIO = AIC.INCI_CUSTOMER_ID
            LEFT OUTER JOIN VENDOR ON
                VENDOR.VENDORID = AIC.INCI_VENDOR_ID
            LEFT OUTER JOIN COUNTRY COUNTRYVENDOR ON
                COUNTRYVENDOR.COUNTRYID = VENDOR.COUNTRYID
            LEFT OUTER JOIN ASDK_SERVICE ON
                ASDK_SERVICE.FL_INT_SERVICE_ID = AIC.INCI_SERVICE_ID
            LEFT OUTER JOIN ASDK_SLA ON
                ASDK_SLA.SLA_ID = AIC.INCI_SERVICE_SLA_ID
    ) TMP
ORDER BY
    TIPO_CASO,
    NUMERO_CASO
