SELECT
	A.FL_INT_CI_ID AS 'ID',
	A.FL_STR_CI_NAME AS 'NOMBRE',
	B.stat_name AS 'ESTADO',
	C.description AS 'MODELO',
	A.FL_STR_SERIAL AS 'SERIAL',
	A.FL_STR_ASSETTAG AS 'ETIQUETA DEL INVENTARIO',
	A.FL_STR_DESCRIPTION AS 'DESCRIPCION',
	D.FL_STR_HIERARCHY AS 'CATEGORIA COMPLETA',
	E.description AS 'MARCA',
	F.UNAME AS 'RESPONSABLE',
	A.FL_DAT_CHECKIN_COMPANY AS 'FECHA DE INGRESO A LA COMPAÑIA',
	A.FL_DAT_CHECKOUT_COMPANY AS 'FECHA DE SALIDA DE LA COMPAÑIA',
	G.description AS 'CENTRO DE COSTO',
	CASE WHEN ci_final_status = 1 THEN 'ACTIVO' ELSE 'INACTIVO' END AS 'ESTADO FINAL DEL CI'
FROM
	CI_CONFIGURATION_ITEM AS A
INNER JOIN
	AFW_STATUS AS B
ON (A.FL_INT_ACTUAL_STATUS_ID = B.stat_id)
LEFT JOIN 
	MODEL AS C 
ON (A.FL_STR_MODEL = C.model_id)
INNER JOIN
	CI_TYPE_ITEM AS D
ON (A.FL_INT_TYPE_ITEM_ID = D.FL_INT_TYPE_ITEM_ID)
LEFT JOIN 
	BRAND AS E
ON (A.FL_STR_BRAND_ID = E.brand_id)
LEFT JOIN 
	USUARIOS AS F 
ON (A.FL_INT_USER_INCHARGE_ID = F.CODUSUARIO)
LEFT JOIN
	COST_CENTER AS G
ON (A.FL_STR_COSTCENTER_ID = G.code_id);